title: brenda
description: Guarding the gates of cyberspace with code and conscience. Journey with me as we secure the digital world.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
